services:
  ihugi.webapi.redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
  
  ihugi.mysql:
    image: mysql
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"

volumes:
  db_data:
    
