<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Properties\launchSettings.json" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" >
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
      <PackageReference Include="Quartz" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Ihugi.Application\Ihugi.Application.csproj" />
      <ProjectReference Include="..\..\Ihugi.Domain\Ihugi.Domain.csproj" />
    </ItemGroup>

</Project>
